#!/bin/bash

if [[ -d "$1" ]] ; then
    ls -A "$1" 2>&1 | cat > /dev/null

    pstat=("${PIPESTATUS[@]}")

    status=0
    for x in "${pstat[@]}" ; do
        if [[ "$x" -ne 0 ]] ; then
            status=1
            break
        fi
    done

    if [[ "$status" -eq 0 ]] ; then
        echo "      ((( Directory )))"
        ls -A "$1" 2>&1
    else
        echo "      ????? Directory no preview ????? "
    fi

else
    head -c 16 "$1" 2>&1 | tr -d "\0" > /dev/null

    pstat=("${PIPESTATUS[@]}")

    status=0
    for x in "${pstat[@]}" ; do
        if [[ "$x" -ne 0 ]] ; then
            status=1
            break
        fi
    done

    if [[ "$status" -eq 0 ]] ; then
        head -c 4096 "$1" 2>&1 | tr -d "\0"
    else
        echo "      ????? File no preview ????? "
    fi
fi

