#!/bin/bash

if [[ -d "$1" ]] ; then
    echo "      ((( Directory )))"
    ls -A "$1"
else
    # This line stopped working for some reason
    #head -c 4096 "$1" 2>&1 | tr -d "\0" | read -r prev

    head -c 16 "$1" 2>&1 | tr -d "\0" > /dev/null

    pstat=("${PIPESTATUS[@]}")

    ok=0
    for x in "${pstat[@]}" ; do
       if [[ "$x" -ne 0 ]] ; then
           ok=1
           break
       fi
    done


    if [[ "$ok" -eq 0 ]] ; then
        head -c 4096 "$1" | tr -d "\0"
    else
        echo "      ????? No preview ????? "
    fi
fi

